server.port=8182

spring.healthapp.datasource.url=jdbc:postgresql://192.192.192.209:5432/gphc
spring.healthapp.datasource.username=appuser
spring.healthapp.datasource.password=Gphc@#$321
spring.healthapp.datasource.driver-class-name=org.postgresql.Driver

spring.auth.datasource.url=jdbc:postgresql://192.192.192.209:5432/authserver
spring.auth.datasource.username=keycloak
spring.auth.datasource.password=12345678
spring.auth.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

origins = http://192.192.192.209,http://localhost:8081

auth.user.add = http://192.192.192.209:8181/api/v1/users/add
auth.user.role-map = http://192.192.192.209:8181/api/v1/users/role-map
auth.role.user = http://192.192.192.209:8181/api/v1/roles/user
profile.default.roleId = b1af50d5-3d66-45fa-a044-23d96b422668
profile.default.roleName = PATIENT

ehr = http://10.7.1.32:8084/ehrbase/rest
ehr.register = /openehr/v1/ehr
ehr.composition = /ecis/v1/composition
fhir = http://10.7.1.32:8083/fhir/Patient

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

file.upload-dir=./uploads