server.port=8182

spring.healthapp.datasource.url=jdbc:postgresql://192.192.192.209:5432/gphc
spring.healthapp.datasource.username=appuser
spring.healthapp.datasource.password=Gphc@#$321
spring.healthapp.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
